# Generated by Django 2.2 on 2019-10-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20181204_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.TextField(max_length=100, null=True, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('contactno', models.BigIntegerField()),
                ('gender', models.TextField()),
                ('password', models.TextField(max_length=15, null=True)),
            ],
        ),
    ]
