# Generated by Django 2.2 on 2019-10-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_user_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_reg',
        ),
    ]
