# Generated by Django 2.2 on 2019-10-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_delete_user_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character ISBN number', max_length=13, verbose_name='ISBN'),
        ),
    ]
